# Generated by Django 5.1.1 on 2024-10-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="images/")),
                ("size", models.IntegerField()),
                ("field1", models.CharField(blank=True, max_length=100, null=True)),
                ("field2", models.CharField(blank=True, max_length=100, null=True)),
                ("field3", models.CharField(blank=True, max_length=100, null=True)),
                ("field4", models.CharField(blank=True, max_length=100, null=True)),
                ("field5", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
