# Generated by Django 5.1.1 on 2024-10-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_itemimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
    ]
