# Generated by Django 5.1.1 on 2024-10-18 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0005_item2_itemimage2"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemimage2",
            name="image",
            field=models.ImageField(upload_to="item_images2/"),
        ),
        migrations.CreateModel(
            name="Item3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_item", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="images/")),
                ("video", models.FileField(blank=True, null=True, upload_to="videos/")),
                (
                    "area_in_meters",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("room", models.IntegerField(default=0)),
                ("kitchen", models.IntegerField(default=0)),
                ("bathroom", models.IntegerField(default=0)),
                ("hall", models.IntegerField(default=0)),
                ("Plakona", models.IntegerField(default=0)),
                (
                    "added_by_name",
                    models.CharField(editable=False, max_length=150, null=True),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemImage3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="item_images3/")),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="order.item3",
                    ),
                ),
            ],
        ),
    ]
